<?php

$kursk_krim = [
    [
        'viezd' => '14 Июня',
        'vozvrashenie' => '25 Июня',
        'june_day_count' => '10',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '23 Июня',
        'vozvrashenie' => '04 Июля',
        'june_day_count' => '7',
        'july_day_count' => '3',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '02 Июля',
        'vozvrashenie' => '13 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '11 Июля',
        'vozvrashenie' => '22 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '20 Июля',
        'vozvrashenie' => '31 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '29 Июля',
        'vozvrashenie' => '09 Августа',
        'june_day_count' => '0',
        'july_day_count' => '2',
        'august_day_count' => '8',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '07 Августа',
        'vozvrashenie' => '18 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '16 Августа',
        'vozvrashenie' => '27 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '25 Августа',
        'vozvrashenie' => '05 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '6',
        'september_day_count' => '4',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '03 Сентября',
        'vozvrashenie' => '14 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '10',
        'direction' => 'Курск - Крым',
    ],
    [
        'viezd' => '12 Сентября',
        'vozvrashenie' => '23 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '10',
        'direction' => 'Курск - Крым',
    ],
];
