<?php

$kursk_lazarevskoe = [
    [
        'viezd' => '11 Июня',
        'vozvrashenie' => '22 Июня',
        'june_day_count' => '10',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '20 Июня',
        'vozvrashenie' => '1 Июля',
        'june_day_count' => '1',
        'july_day_count' => '9',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '29 Июня',
        'vozvrashenie' => '10 Июля',
        'june_day_count' => '1',
        'july_day_count' => '9',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '8 Июля',
        'vozvrashenie' => '19 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '17 Июля',
        'vozvrashenie' => '28 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '26 Июля',
        'vozvrashenie' => '6 Августа',
        'june_day_count' => '0',
        'july_day_count' => '5',
        'august_day_count' => '5',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '4 Августа',
        'vozvrashenie' => '15 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '13 Августа',
        'vozvrashenie' => '24 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '22 Августа',
        'vozvrashenie' => '2 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '9',
        'september_day_count' => '1',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '31 Августа',
        'vozvrashenie' => '11 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '10',
        'direction' => 'Курск - Лазаревское',
    ],
    [
        'viezd' => '9 Сентября',
        'vozvrashenie' => '-',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '10',
        'direction' => 'Курск - Лазаревское',
    ],
];
