<?php

$reis_data = [
    0 => [
        'viezd' => '08 Июня',
        'vozvrashenie' => '19 Июня',
        'june_day_count' => '10',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    1 => [
        'viezd' => '17 Июня',
        'vozvrashenie' => '28 Июня',
        'june_day_count' => '10',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    2 => [
        'viezd' => '26 Июня',
        'vozvrashenie' => '07 Июля',
        'june_day_count' => '4',
        'july_day_count' => '6',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    3 => [
        'viezd' => '05 Июля',
        'vozvrashenie' => '16 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    4 => [
        'viezd' => '14 Июля',
        'vozvrashenie' => '25 Июля',
        'june_day_count' => '0',
        'july_day_count' => '10',
        'august_day_count' => '0',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    5 => [
        'viezd' => '23 Июля',
        'vozvrashenie' => '03 Августа',
        'june_day_count' => '0',
        'july_day_count' => '8',
        'august_day_count' => '2',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    6 => [
        'viezd' => '01 Августа',
        'vozvrashenie' => '12 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    7 => [
        'viezd' => '10 Августа',
        'vozvrashenie' => '21 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    8 => [
        'viezd' => '19 Августа',
        'vozvrashenie' => '30 Августа',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '10',
        'september_day_count' => '0',
        'direction' => 'Курск - Анапа',
    ],
    9 => [
        'viezd' => '28 Августа',
        'vozvrashenie' => '08 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '3',
        'september_day_count' => '7',
        'direction' => 'Курск - Анапа',
    ],
    10 => [
        'viezd' => '06 Сентября',
        'vozvrashenie' => '17 Сентября',
        'june_day_count' => '0',
        'july_day_count' => '0',
        'august_day_count' => '0',
        'september_day_count' => '10',
        'direction' => 'Курск - Анапа',
    ],
    11 => [
        'viezd' => '15 Сентября',
        'vozvrashenie' => '26 Сентября',
        'june_day_count' => '',
        'july_day_count' => '',
        'august_day_count' => '',
        'september_day_count' => '10',
        'direction' => 'Курск - Анапа',
    ],
];
